### ISSUE TITLE
Klass.js doesn't work

### ISSUE THREAD

**Issue by matthew-dean** [ded/klass#8]
As soon as Google Chrome comes across the Klass file, it just spits out the error "TypeError: undefined is not a function." It's also not working in Internet Explorer.

**Comment by saran110313** [comment]
function klass() {
      this.initialize.apply(this, arguments);
    }
how to solve  Uncaught TypeError: Cannot read property 'apply' of undefined  this problem...

**Comment by saran110313** [comment]
I'm receiving this error originating from fabric.js

Uncaught TypeError: Cannot read property 'apply' of undefined

function klass() {
(ln: 1690) --> this.initialize.apply(this, arguments);
}

**Comment by ded** [comment]
@saran110313 it's hard to tell where the real problem is without more context.

**Comment by saran110313** [comment]
function klass() {
    (In: 1690)-->  this.initialize.apply(this, arguments);
    }

Uncaught TypeError: Cannot read property 'apply' of undefined
i m working nodejs with fabric.js.

**Comment by saran110313** [comment]
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
how to solve this error in fabric.js
